travis:
  secure:
    BINSTAR_TOKEN: jD0QWV8j5ciodemSN3xVdBqM5LCUWcnT72cmO+JWPvGDlBOywwZr0mXkNS0IVVWyDgd80Z65zTRx4vDim9+fLQWP/WX7TOmKDNm2XqAVor1/hPAxQFSlca9Nz5fASC/gKLTrvYIOJVGGMsiBhJ0J81L/ndDd7CkFLNwj7XBO9eoXePiqvqxyUrDpdfJ6z76sRudFVBkn1GzKJmT7lb+1YOCnFvTtqXbKRbBlvMN5dXPK7I9G1wK0B1PDdXTUaB9gTD/mo0G5ruBsGtzsqfkYFHx8BgU9GTOXL8CCIG/DLn6u1u4VCj9uur1Wb/ZA1CfSah8jsZUQ85ZHdMFaEWhmCb6MdUKPq21Bg94wstUYN5FxFDve3DrYPmXnetAtYCG0oQlemaH1HWAPw+/n3N5/Dp/WfhDmSIIu5E54KU7X5Vs42LTgRLsEiEnyeIP9oQxcA/1i+DsEMcnPe/yigNx+WMeUINIV6nhiFiEiws4fRatnmeSDMLWlWJu74aUj3Al4Jj4RmvU8J6OzgjLk5n5WnoTrBNFc9fVwttA3/ORU9SyVOgK8Buq77/oDqNBJv49IRWe+1isbyAHpgu++ivFKkCrBm02w8abcF4MDVkwW6Zmv0YsChIKajOT5unBWhu+5g7nqH8GFCvlHV2DyAyvNg8PGHt6zG+q3tepR/h9efl8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
